### ISSUE TITLE
NaiveDatetimePicker model not found

### ISSUE THREAD

**Issue by Sleepyhead5** [vidartf/ipydatetime#10]
Reproduce:
OS: ubuntu 18.04 or Windows 10
python --version Python 3.8.1
```
pip install jupyterlab==2.1.4
pip install ipydatetime
jupyter labextension install jupyter-widget-datetime @jupyter-widgets/jupyterlab-manager
jupyter lab
```
in the cell I have
```
import ipydatetime
import ipywidgets
import datetime
ipydatetime.NaiveDatetimePicker()
```
and what I get is `Error displaying widget: model not found.`

Regular `ipydatetime.DatetimePicker()` widgets display fine for me.

It looks like this might be resolved by #9 but that this update hasn't been pushed yet to https://www.npmjs.com/package/jupyter-widget-datetime

**Comment by vidartf** [comment]
Nice catch

**Comment by vidartf** [comment]
Should be released now, but it might take a few hours to propagate.
