### ISSUE TITLE
Loading widget... and widget never loads

### ISSUE THREAD

**Issue by activescott** [vidartf/ipydatetime#11]
I'm on Jupyterlab Version 1.2.5 and used the following command in a python notebook to install it (which I use for other packages successfully):

    !python3 -m pip install ipydatetime

and it installed `ipydatetime-1.1.1-py2.py3-none-any.whl`

When I run the following code in a notebook:

```
import ipydatetime
import ipywidgets
import datetime

time_picker = ipydatetime.TimePicker()

time_picker
```

It simply says `Loading widget...` below the cell and never changes. I also tried other widgets in the package and get the same behavior. 

Any ideas?

**Comment by vidartf** [comment]
If you are using Jupyterlab you probably also need to run `jupyter labextension install @jupyter-widgets/jupyterlab-manager`.
