### ISSUE TITLE
TimePicker in 12-hour AM/PM format and cannot be changed to 24-hour

### ISSUE THREAD

**Issue by samzhangcode** [vidartf/ipydatetime#13]
TimePicker widget `ipydatetime.TimePicker()` in chrome is displayed in 12-hour (AM/PM) format and there is no way to change it to 24-hour format.

Below screenshot is use [time picker doc ](https://ipydatetime.readthedocs.io/en/latest/examples/introduction.html#The-time-picker)as example:
![Screenshot at Feb 16 15-52-17](https://user-images.githubusercontent.com/2107221/108120275-03a8b180-706f-11eb-8eb2-36d81ef82a3d.png)

Browser: Chrome `Version 88.0.4324.182 (Official Build) (x86_64)`
Python Version: 3.8.0
jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : 5.0.2
ipython          : 7.20.0
ipykernel        : 5.4.3
jupyter client   : 6.1.11
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.2
traitlets        : 5.0.5

Also in safari browser, it's a plain text box.
![Screenshot at Feb 16 15-51-43](https://user-images.githubusercontent.com/2107221/108120189-e542b600-706e-11eb-9be8-3ad590f1d250.png)

**Comment by vidartf** [comment]
ipydatetime uses the native browser controls. This means you are entirely at the mercy of the functionality and behavior of the browser. I guess the use of 24h vs PM/AM clock in Chrome depends on your locale settings? At least, I am getting the 24h picker using the exact same version of Chrome (on Windows 10) where my system is configured to use 24h time.

**Comment by vidartf** [comment]
You can confirm the browser behavior here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

If you are seeing something different there, it could be an ipydatetime issue.

EDIT: I see that the page mentions that:
> [...] in 12 or 24-hour format depending on operating system locale,

**Comment by samzhangcode** [comment]
Thanks, @vidartf. You're absolutely right. It is because my mac OS is set to be 12h. After I changing OS time to 24h, the widget is in 24h as well.
