### ISSUE TITLE
No output when used jupyter-notebook : 6.2.0

### ISSUE THREAD

**Issue by sivaji1233** [vidartf/ipydatetime#15]
![image](https://user-images.githubusercontent.com/49131628/117186696-b7812980-ada0-11eb-95c6-f68714fee0e4.png)

Nothing loads

**Comment by vidartf** [comment]
Two things to check:
- Is the nbextension installed and enabled? Run `jupyter nbextension list` to check.
- Are there any errors in the browsers Developer Console? A typical shortcut it Ctrl + Shift + J. 

Also, which version of ipydatetime is installed? And which version of ipywidgets? These can be found via `pip freeze`.

**Comment by vidartf** [comment]
Closing due to lack of details.
