### ISSUE TITLE
DatetimePicker and NaiveDatetimePicker None

### ISSUE THREAD

**Issue by silkreeling** [vidartf/ipydatetime#18]
Great product, thank you!  I noticed, when setting the date-time via website, then clearing the date, the variable 'value' in function _validate_tz is None.  So when the condition is checked the variable 'value' does not have an attribute tzinfo, because it is None.

```
~\miniconda3\lib\site-packages\ipydatetime\datetime_widget.py in _validate_tz(self, value)
     54 
     55     def _validate_tz(self, value):
---> 56         if value.tzinfo is None:

AttributeError: 'NoneType' object has no attribute 'tzinfo'
```

For now as a work around I've been doing this:

```
 def _validate_tz(self, value):
        if value:
            if value.tzinfo is not None:
                raise TraitError('%s values needs to be timezone unaware' % (self.__class__.__name__,))
        return value
```

**Comment by vidartf** [comment]
As the datetime widgets are now in the ipywidgets package, I'm closing this in favor of https://github.com/jupyter-widgets/ipywidgets/issues/3500

**Comment by vidartf** [comment]
(Please add any report you have of which versions of packages/python you are using on that issue)
