### ISSUE TITLE
min and max have no effect on keyboard entry

### ISSUE THREAD

**Issue by davidbrochart** [vidartf/ipydatetime#2]
Setting a `min` or a `max` value effectively constrains the calendar GUI, but one can still enter any date from the keyboard, even if it doesn't respect the bounds.

**Comment by vidartf** [comment]
Which browser do you use? Browser support for the date/time inputs varies greatly.

**Comment by davidbrochart** [comment]
You're right, it was in Chromium but I can see that it works well in Firefox.

**Comment by vidartf** [comment]
Closing as an upstream issue then.
