### ISSUE TITLE
Support for `step` with `DatetimePicker`?

### ISSUE THREAD

**Issue by loren** [vidartf/ipydatetime#7]
I don't seem to be able to set seconds/millis with the `DateTimePicker`:

```
ipydatetime.DatetimePicker(step=0.001)
```

If I pass in something with millis, it displays them:
```
ipydatetime.DatetimePicker(value=datetime.now(tz=pytz.utc))
```
but when I try to edit them, I get a hint/tooltip saying "Please enter a valid value. The two nearest valid values are...". If I edit the value to be rounded to the nearest minute, the validation passes.

**Comment by vidartf** [comment]
Which browsers did you try this with, and is the behavior consistent across all of them? There are quite a few differences in how they implement the native datetime pickers.

**Comment by loren** [comment]
Chrome 83.0.4103.61 and Edge 44.17763.831.0 on Win 10.

What's odd to me is that the seconds and millis pickers are there, but there's some validation logic going on under the hood around `step` that requires me to round the times to the minute.

**Comment by vidartf** [comment]
Ah, you are right that the datetime picker does not support step currently. I think I originally skipped on implementing it as some browsers don't support it, but that shouldn't really prevent users from accessing it.

**Comment by vidartf** [comment]
Closing this as the widgets are now available in ipywidgets package itself, and I'm archiving this package/repo.
