### ISSUE TITLE
Cannot observe when value is set to None

### ISSUE THREAD

**Issue by noobymcnoob** [vidartf/ipydatetime#8]
See this code:

```
import ipydatetime

picker = ipydatetime.NaiveDatetimePicker()
picker.observe(print,'value')
display(picker)
```

When I set the date + time, I get a print statement as expected:

![image](https://user-images.githubusercontent.com/38162004/87229090-58ff4080-c373-11ea-92f6-e190db9f6814.png)

However, clearing the value shows a problem:

```
venv/lib/python3.8/site-packages/ipydatetime/datetime_widget.py in _validate_tz(self, value)
    135 
    136     def _validate_tz(self, value):
--> 137         if value.tzinfo is not None:
    138             raise TraitError('%s values needs to be timezone unaware' % (self.__class__.__name__,))
    139         return value

AttributeError: 'NoneType' object has no attribute 'tzinfo'
```

Since I don't need the min/max validation, I just overrode the picker to avoid a `None` value as follows:

```
@register
class DateTimePicker(ipydatetime.NaiveDatetimePicker):
    @validate('value')
    def _validate_value(self,proposal):
        return proposal['value']

    @validate('min')
    def _validate_min(self,proposal):
        return proposal['value']

    @validate('max')
    def _validate_max(self,proposal):
        return proposal['value']

```

However, there is still an issue in the JS sid when I clear the time or date value:

![image](https://user-images.githubusercontent.com/38162004/87229431-d926a580-c375-11ea-9ab0-3e1b9f72014f.png)

Unfortunately, I do not know enough to fix this but I thought perhaps this can help you fix it if you are interested.

**Comment by vidartf** [comment]
I think the validator functions just need a `if value is None: return value` at the start.

**Comment by vidartf** [comment]
As the datetime widgets are now in the ipywidgets package itself, I'm closing this in favor of https://github.com/jupyter-widgets/ipywidgets/issues/3500
